--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gear/Pictures/Wal/saturn.png"

-- Special
background="#080708"
foreground="#dfddd2"
cursor="#dfddd2"

-- Colors
color0="#080708"
color1="#74706E"
color2="#837C78"
color3="#88827C"
color4="#798185"
color5="#9A9A94"
color6="#C0BFB1"
color7="#dfddd2"
color8="#9c9a93"
color9="#74706E"
color10="#837C78"
color11="#88827C"
color12="#798185"
color13="#9A9A94"
color14="#C0BFB1"
color15="#dfddd2"
