# Shell variables
# Generated by 'wal'
wallpaper='/home/gear/Pictures/Wal/saturn.png'

# Special
background='#080708'
foreground='#dfddd2'
cursor='#dfddd2'

# Colors
color0='#080708'
color1='#74706E'
color2='#837C78'
color3='#88827C'
color4='#798185'
color5='#9A9A94'
color6='#C0BFB1'
color7='#dfddd2'
color8='#9c9a93'
color9='#74706E'
color10='#837C78'
color11='#88827C'
color12='#798185'
color13='#9A9A94'
color14='#C0BFB1'
color15='#dfddd2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
