--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gear/Pictures/wallpapers/MXSyPMM.jpg"

-- Special
background="#221b3c"
foreground="#e6e6e0"
cursor="#e6e6e0"

-- Colors
color0="#221b3c"
color1="#5691D4"
color2="#E1A296"
color3="#D0ADA0"
color4="#9AA9D2"
color5="#B3C7D4"
color6="#D2D6D2"
color7="#e6e6e0"
color8="#a1a19c"
color9="#5691D4"
color10="#E1A296"
color11="#D0ADA0"
color12="#9AA9D2"
color13="#B3C7D4"
color14="#D2D6D2"
color15="#e6e6e0"
