# Shell variables
# Generated by 'wal'
wallpaper='/home/gear/Pictures/wallpapers/MXSyPMM.jpg'

# Special
background='#221b3c'
foreground='#e6e6e0'
cursor='#e6e6e0'

# Colors
color0='#221b3c'
color1='#5691D4'
color2='#E1A296'
color3='#D0ADA0'
color4='#9AA9D2'
color5='#B3C7D4'
color6='#D2D6D2'
color7='#e6e6e0'
color8='#a1a19c'
color9='#5691D4'
color10='#E1A296'
color11='#D0ADA0'
color12='#9AA9D2'
color13='#B3C7D4'
color14='#D2D6D2'
color15='#e6e6e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
